dazpm_cmd_rebuild() {
  mkdir -p \
    "$DAZPM_BIN_DIR" \
    "$DAZPM_FUNCTIONS_DIR" \
    "$DAZPM_PLUGINS_DIR" \
    "$DAZPM_COMPLETIONS_DIR"

  cat > "$DAZPM_LOADER" <<'LOADER'
# Generated by dazpm. Do not edit manually.

export DAZPM_HOME="${XDG_DATA_HOME:-$HOME/.local/share}/dazpm"
export PATH="$DAZPM_HOME/bin:$PATH"

fpath=("$DAZPM_HOME/functions" "$DAZPM_HOME/completions" $fpath)

for fn in "$DAZPM_HOME"/functions/*(N:t); do
  autoload -Uz "$fn"
done

for plugin in "$DAZPM_HOME"/plugins/*.zsh(N); do
  source "$plugin"
done

autoload -Uz compinit
compinit -d "$DAZPM_HOME/.zcompdump"
LOADER

  dazpm_log "rebuilt loader"
  dazpm_ui_kv "path" "$DAZPM_LOADER"
}
