dazpm_cmd_rebuild() {
  mkdir -p \
    "$DAZPM_BIN_DIR" \
    "$DAZPM_FUNCTIONS_DIR" \
    "$DAZPM_PLUGINS_DIR" \
    "$DAZPM_COMPLETIONS_DIR"

  cat > "$DAZPM_LOADER" <<EOF
# Generated by dazpm. Do not edit manually.

export DAZPM_HOME="$DAZPM_HOME"
export PATH="\$DAZPM_HOME/bin:\$PATH"

fpath=("\$DAZPM_HOME/functions" "\$DAZPM_HOME/completions" \$fpath)

for plugin in "\$DAZPM_HOME"/plugins/*.zsh(N); do
  source "\$plugin"
done

autoload -Uz compinit
compinit
EOF

  dazpm_log "rebuilt loader: $DAZPM_LOADER"
}
