# dazpm config

: "${DAZPM_PREFIX:=${PREFIX:-$HOME/.local}}"
: "${DAZPM_SHARE_DIR:=$DAZPM_PREFIX/share}"
: "${DAZPM_BIN_ROOT:=$DAZPM_PREFIX/bin}"

: "${XDG_CONFIG_HOME:=$HOME/.config}"
: "${XDG_CACHE_HOME:=$HOME/.cache}"

export DAZPM_PREFIX
export DAZPM_SHARE_DIR
export DAZPM_BIN_ROOT

export DAZPM_HOME="${DAZPM_HOME:-$DAZPM_SHARE_DIR/dazpm-home}"
export DAZPM_CONFIG_DIR="${DAZPM_CONFIG_DIR:-$XDG_CONFIG_HOME/dazpm}"
export DAZPM_CACHE_DIR="${DAZPM_CACHE_DIR:-$XDG_CACHE_HOME/dazpm}"

export DAZPM_PACKAGES_DIR="$DAZPM_HOME/packages"
export DAZPM_RECORDS_DIR="$DAZPM_HOME/records"
export DAZPM_BIN_DIR="$DAZPM_HOME/bin"
export DAZPM_FUNCTIONS_DIR="$DAZPM_HOME/functions"
export DAZPM_PLUGINS_DIR="$DAZPM_HOME/plugins"
export DAZPM_COMPLETIONS_DIR="$DAZPM_HOME/completions"
export DAZPM_LOADER="$DAZPM_HOME/init.zsh"
export DAZPM_LOCKFILE="$DAZPM_HOME/dazpm.lock"
